### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by rebel216**
Awesome Books using ES6 modules

### CODE REVIEW

**Review by omarsalem7 — CHANGES_REQUESTED** [review]
Hi @rebel216 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

you-are-near

## Highlights
- No linter errors ✔️
- The current date is displayed below the navigation bar by using luxon ✔️

## Required Changes ♻️

- [ ] Kindly divide your code into reasonable modules and use export/import for modules. And also consider using `arrow` syntax for functions. I suggest you can make module for UI and a module for removing and adding books and this is up to you.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rebel216** [comment]
> Hi @rebel216 😊,
> 
> Good job so far! 👏 You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there!
> 
> you-are-near [ you-are-near ](https://camo.githubusercontent.com/24e9f6bcfc9c66d6f90ce4fc937ec10b7ba92a648dadb764fb2c37246d36fbce/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f53535231374b36795a5776474359726655682f67697068792e676966) [ ](https://camo.githubusercontent.com/24e9f6bcfc9c66d6f90ce4fc937ec10b7ba92a648dadb764fb2c37246d36fbce/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f53535231374b36795a5776474359726655682f67697068792e676966)
> 
> ## Highlights
> * No linter errors ✔️
> * The current date is displayed below the navigation bar by using luxon ✔️
> 
> ## Required Changes ♻️
> * [ ]  Kindly divide your code into reasonable modules and use export/import for modules. And also consider using `arrow` syntax for functions. I suggest you can make module for UI and a module for removing and adding books and this is up to you.
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

have created modules in modules folder.
The project was already approved and submitted earlier, I am just repeating the module so submitted it again.

**Review by mmsesay — CHANGES_REQUESTED** [review]
Hi @rebel216,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
 - Good Readme :heavy_check_mark: 
 - No linter error :heavy_check_mark: 
 - Good PR title & summary :heavy_check_mark:

 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mmsesay** [comment]
- [ ] Just as the previous reviewer suggested. Please make use of export/import for modules, arrow functions and const/let correctly. You can do something like wrapping the event listeners `/modules/function.js` inside a function and export that function. Wrapping event listeners inside a function will give us more control on how addEventListener interacts with our application. 

Note: I also understand that this project was approved during your first time going through this module. I guess it skipped the reviewer at that time to point out some of these ES6 concept and best practices before approving. I must say your code structure is good and would suggest you implement the required changes to make it better.

**Comment by mmsesay** [comment]
- [ ] Just as the previous reviewer suggested. Please make use of export/import for modules, arrow functions and const/let correctly. You can do something like wrapping the event listeners `/modules/function.js` inside a function and export that function. Wrapping event listeners inside a function will give us more control over how addEventListener interacts with our application. 

Note: I also understand that this project was approved during your first time going through this module. I guess it skipped the reviewer at that time to point out some of these ES6 concepts and best practices before approval. I must say your code structure is good and would suggest you please implement the required changes to make it better.

**Review by Davidosky007 — APPROVED** [review]
Hi @rebel216 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Well written commit messgaes 👍 
* No linter errors 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
